name: JD_jdzz

on:
  repository_dispatch:
  release:
    types: published
  # push:
  #   branches:
  #     - master
  schedule:
    - cron: 0 23 * * *
  watch:
    types: started
    
env:
  JD_COOKIE: ${{ secrets.JD_COOKIE }}
  JD_DUAL_COOKIE: ${{ secrets.JD_DUAL_COOKIE }}
  PUSH_KEY: ${{ secrets.PUSH_KEY }}
  UPLOAD_BESULT_DIR: true

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout codes
              uses: actions/checkout@v2
              
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                node-version: '12.x'
                
            - name: Run install
              run: npm install
              
            - name: Run Script
              run: node jd_jdzz.js
              
            - name: Run JD_club_lottery
              run: node jd_club_lottery.js
              
            - name: Run JD_cash
              run: node jd_cash.js
              
            - name: Run JD_fruit
              run: node jd_fruit.js
              
            - name: Run JD_plantBean.js
              run: node jd_plantBean.js
              
            - name: Run jd_speed
              run: node jd_speed.js
              
            - name: Run unsubscribe
              run: node jd_unsubscribe.js
            
            - name: Run jd_syj
              run: node jd_syj.js
              
            - name: Run jx
              run: node jx_sign.js
                
            - name: Upload result file
              uses: actions/upload-artifact@master
              if: env.UPLOAD_BESULT_DIR == 'true'
              with:
                name: result
                path: ./*.txt


